In [28]:
import pandas as pd

# Load the data
file_path = "phenotypes_genotypes_Chr09.csv"  # Update with the path to your file
df = pd.read_csv(file_path, index_col=0)

# Transpose the dataframe for easier column-based filtering
df = df.T

# coerce the columns to numeric
bc_columns = ["BC_Binary", "BC_5_Class"]
for col in bc_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Define conditions
conditions = {
    "1/1_0/1_BC_Binary=2": (df["Chr09_46098776"] == "1/1") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 2),
    "0/1_0/0_BC_Binary=2": (df["Chr09_46098776"] == "0/1") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 2),
    "1/1_0/0_BC_Binary=2": (df["Chr09_46098776"] == "1/1") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 2),
    "0/0_0/0_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 1),
    "0/1_0/1_BC_Binary=1": (df["Chr09_46098776"] == "0/1") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 1),
    "0/0_0/1_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 1),
    "0/0_1/1_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "1/1") & (df["BC_Binary"] == 1)

}

# Calculate averages and counts
results = []
for condition_name, condition in conditions.items():
    subset = df[condition]
    average = subset["BC_5_Class"].mean()
    count = subset.shape[0]
    results.append({"Condition": condition_name, "Average_BC_5_Class": average, "Count": count})

# Convert results to a DataFrame for display
results_df = pd.DataFrame(results)

# Save or display results
print(results_df)

             Condition  Average_BC_5_Class  Count
0  1/1_0/1_BC_Binary=2                2.00      1
1  0/1_0/0_BC_Binary=2                3.48     25
2  1/1_0/0_BC_Binary=2                3.00      1
3  0/0_0/0_BC_Binary=1                1.00      1
4  0/1_0/1_BC_Binary=1                1.00     21
5  0/0_0/1_BC_Binary=1                1.00     29
6  0/0_1/1_BC_Binary=1                1.00     33

In [35]:
# Define conditions
conditions = {
    "1/1_0/1_BC_Binary=2": (df["Chr09_46098776"] == "1/1") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 2),
    "0/1_0/0_BC_Binary=2": (df["Chr09_46098776"] == "0/1") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 2),
    "1/1_0/0_BC_Binary=2": (df["Chr09_46098776"] == "1/1") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 2),
    "0/0_0/0_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "0/0") & (df["BC_Binary"] == 1),
    "0/1_0/1_BC_Binary=1": (df["Chr09_46098776"] == "0/1") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 1),
    "0/0_0/1_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "0/1") & (df["BC_Binary"] == 1),
    "0/0_1/1_BC_Binary=1": (df["Chr09_46098776"] == "0/0") & (df["Chr09_49257768"] == "1/1") & (df["BC_Binary"] == 1)

}

df_og[conditions["0/0_0/0_BC_Binary=1"]]

          BC_Binary  BC_5_Class Chr09_46098776 Chr09_49257768
F2-06-54          1           1            0/0            0/0

In [23]:
df[conditions["1/1_0/0_BC_Binary=2"]]

           BC_Binary  BC_5_Class Chr09_46098776 Chr09_49257768
F2-06-132          2           3            1/1            0/0

In [22]:
import os

vcf = list()

for file in os.listdir():
    if file.endswith(".png"):
        vcf.append(file)
        
print(vcf)

['trait characteristics distribution.png', 'LAB_a_pheno_lg9_QTLs.png', 'distribution_of_colorimeter_trait_values.png', 'LAB_a_pheno_QTLs.png', 'cim_bracts_A_full_image_permutations_with_threshold_QTLs.png', 'missing filtering.png', 'categorical_pheno_QTLs.png', 'distribution_of_trait_values.png', 'full_bract_all_metrics_QTLs.png', 'distribution_of_image_trait_values.png', 'rqtl full_A. plot test.png', 'distribution_of_binary_trait_values.png', 'leaves_all_pheno_QTLs.png', 'Distribution of Markers Across Genome.png', 'segregation filtering.png', 'all_but_binary_pheno_QTLs.png', 'leaves_5_class_pheno_QTLs.png', 'image_all_lg9_QTLs.png', 'leaves_5class_lg9_QTLs.png', 'all_QTLs.png', 'genetic map vs. marker position.png', 'cim_bracts_A_colorimeter_permutations_with_threshold_r2ls_QTLs.png', 'cim_bracts_A_colorimeter_permutations_with_threshold_QTLs.png', 'Filter_individuals.png', 'leaves_5_pheno_with_threshold_QTLs.png', 'leaves_binary_with_threshold_QTLs.png']

In [25]:
len(df[df["BC_Binary"] == 2])

30

In [26]:
df[df["BC_Binary"] == 2]

            BC_Binary  BC_5_Class Chr09_46098776 Chr09_49257768
F2-06-02            2           2            1/1            0/1
F2-06-07            2           4            0/1            0/0
F2-06-112           2           4            0/1            0/0
F2-06-117           2           5            0/1            0/0
F2-06-118           2           5            0/0            0/1
F2-06-129           2           4            0/1            0/0
F2-06-130           2           4            0/1            0/0
F2-06-132           2           3            1/1            0/0
F2-06-137           2           4            0/1            0/0
F2-06-138           2           5            0/1            0/0
F2-06-147           2           3            0/1            0/0
F2-06-21            2           4            0/1            0/0
F2-06-220B          2           3            0/1            0/0
F2-06-235           2           4            0/1            0/0
F2-06-245           2           5            0/1            0/0
F2-06-248           2           3            0/1            0/0
F2-06-258           2           2            0/1            0/0
F2-06-259           2           2            0/1            0/0
F2-06-266           2           2            0/1            0/1
F2-06-271           2           3            0/1            0/0
F2-06-44            2           3            0/1            0/0
F2-06-46            2           4            0/1            0/0
F2-06-48            2           3            0/1            0/0
F2-06-53            2           3            0/1            0/0
F2-06-77            2           2            0/1            0/0
F2-06-78            2           4            ./.            0/0
F2-06-79R           2           4            0/1            0/0
F2-06-85            2           2            0/1            0/0
F2-06-87            2           3            0/1            0/0
F2-06-92            2           4            0/1            0/0

In [19]:
import pandas as pd

# Load the data
file_path = "phenotypes_genotypes_Chr09_409.csv"  # Update with the path to your file
df = pd.read_csv(file_path, index_col=0)

# Transpose the dataframe for easier column-based filtering
df = df.T

# coerce the columns to numeric
bc_columns = ["BC_Binary", "BC_5_Class"]
for col in bc_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    
print(len(df))

print(len(df[(df["Chr09_40934664"] == df["Chr09_40934714"]) & (df["Chr09_40934664"] == df["Chr09_40934715"]) & (df["Chr09_40934664"] == df["Chr09_41182684"])]))

116
116

In [ ]:
## so we know that the genotypes are the same at the markers Chr09_40934664 - Chr09_41182684. Let's double check that they match up with the phenotypes

In [16]:
# Define conditions
conditions = {
    "1/1_BC_Binary=1": (df["Chr09_40934664"] == "1/1") & (df["BC_Binary"] == 1),
    "0/1_BC_Binary=1": (df["Chr09_40934664"] == "0/1") & (df["BC_Binary"] == 1),
    "0/0_BC_Binary=1": (df["Chr09_40934664"] == "0/0") & (df["BC_Binary"] == 2)

}

# Calculate averages and counts
results = []
for condition_name, condition in conditions.items():
    subset = df[condition]
    average = subset["BC_5_Class"].mean()
    count = subset.shape[0]
    results.append({"Condition": condition_name, "Average_BC_5_Class": average, "Count": count})

# Convert results to a DataFrame for display
results_df = pd.DataFrame(results)

# Save or display results
print(results_df)

         Condition  Average_BC_5_Class  Count
0  1/1_BC_Binary=1            1.000000     33
1  0/1_BC_Binary=1            1.000000     53
2  0/0_BC_Binary=1            3.535714     28

In [17]:
sum(results_df['Count'])

114

In [ ]:
## these are the two that are "incorrect", but they are barely a blush color, so I think it's the normal blushing of the hets
df[(df["Chr09_40934664"] == "0/1") & (df["BC_Binary"] == 2)]

,BC_Binary,BC_5_Class,Chr09_40934664,Chr09_40934714,Chr09_40934715,Chr09_41182684,Chr09_41873463
F2-06-02,2,2,0/1,0/1,0/1,0/1,0/1
F2-06-266,2,2,0/1,0/1,0/1,0/1,0/1

In [ ]:
# Now let's compile all info into one dataframe

# Load the data
file_path = "phenotypes_genotypes_Chr09.csv"  # Update with the path to your file
df_og = pd.read_csv(file_path, index_col=0)

# Transpose the dataframe for easier column-based filtering
df_og = df_og.T

# coerce the columns to numeric
bc_columns = ["BC_Binary", "BC_5_Class"]
for col in bc_columns:
    df_og[col] = pd.to_numeric(df_og[col], errors="coerce")

           BC_Binary  BC_5_Class Chr09_46098776 Chr09_49257768
F2-06-79W          1           1            0/0            1/1
F2-05-116          1           1            0/0            1/1
F2-06-02           2           2            1/1            0/1
F2-06-03           1           1            0/0            1/1
F2-06-04           1           1            0/0            1/1
...              ...         ...            ...            ...
F2-06-94           1           1            0/0            0/1
F2-06-96           1           1            0/1            0/1
F2-06-97           1           1            0/0            0/1
F2-06-98           1           1            0/0            1/1
F2-06-99           1           1            0/1            0/1

[116 rows x 4 columns]

In [31]:
#df.insert(loc = 7,
#          column = 'Chr09_46098776',
#          value = df_og['Chr09_46098776'])
df.insert(loc = 10,
         column = 'Chr09_49257768',
         value = df_og['Chr09_49257768'])

In [ ]:
# see all of the genotypes within locus of interest.

df[df["BC_Binary"] == 2]

,BC_Binary,BC_5_Class,Chr09_40934664,Chr09_40934714,Chr09_40934715,Chr09_41182684,Chr09_41873463,Chr09_46098776,Chr09_47501485,Chr09_48129837,Chr09_49257768
F2-06-02,2,2,0/1,0/1,0/1,0/1,0/1,1/1,0/0,0/1,0/1
F2-06-07,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-112,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-117,2,5,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-118,2,5,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/1,0/1
F2-06-129,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-130,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-132,2,3,0/0,0/0,0/0,0/0,0/0,1/1,0/0,0/1,0/0
F2-06-137,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-138,2,5,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-147,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-21,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-220B,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-235,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-245,2,5,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-248,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-258,2,2,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-259,2,2,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-266,2,2,0/1,0/1,0/1,0/1,0/1,0/1,0/0,0/1,0/1
F2-06-271,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-44,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-46,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-48,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-53,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-77,2,2,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-78,2,4,0/0,0/0,0/0,0/0,0/0,./.,0/0,0/1,0/0
F2-06-79R,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-85,2,2,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-87,2,3,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0
F2-06-92,2,4,0/0,0/0,0/0,0/0,0/0,0/1,0/0,0/1,0/0